### ISSUE TITLE
Current setup does not allow for publishing following the creation of a release

### ISSUE THREAD

**Issue by fredrikaverpil** [fredrikaverpil/github#3]
When a GitHub Actions workflow (like the release workflow using release-please-action) creates a release, GitHub's default security restrictions prevent that bot-created event from triggering other workflows. This is an intentional security measure to prevent workflow cascade loops.

This is known as the "GitHub Actions workflow triggering limitation" - by default, a workflow run triggered by `github-actions[bot]` cannot trigger another workflow run.

This means that if a repo manages their own `publish.yml`, containing the following:

```yml
on:
  release:
    types: [published]
  workflow_dispatch:
```

...it won't run following the publishing of a release (when the bot does it).

**Comment by fredrikaverpil** [comment]
Potential solution:


1. **Use a Personal Access Token (PAT)**
   Instead of using the default `GITHUB_TOKEN` in your release workflow, you can use a PAT with the `repo` scope:

   ```yml
   - uses: googleapis/release-please-action@v4
     with:
       token: ${{ secrets.PAT_WITH_REPO_SCOPE }}
       # other options...
   ```

2. **Enable workflow_dispatch within the release workflow**
   Modify your release workflow to manually trigger the publish workflow after creating the release:

   ```yml
   - name: Trigger publish workflow
     if: ${{ steps.release.outputs.release_created }}
     uses: peter-evans/repository-dispatch@v2
     with:
       token: ${{ secrets.GITHUB_TOKEN }}
       event-type: publish-release
   ```

   Then update your publish workflow:
   ```yml
   on:
     repository_dispatch:
       types: [publish-release]
     release:
       types: [published]
     workflow_dispatch:
   ```
